lzc-sdk-version: "0.1"
name: Morphos
package: cloud.lazycat.app.morphos
version: 0.6.0
description: 自托管的文件转换工具
homepage: https://github.com/danvergara/morphos
author: danvergara
application:
  subdomain: morphos
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://morphos-server.cloud.lazycat.app.morphos.lzcapp:8080/
services:
  morphos-server:
    image: registry.lazycat.cloud/czyt/danvergara/morphos-server:3ca3c1e09c6ad2bb
    binds:
      - /lzcapp/cache:/tmp
